import './globals.css'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'

const fontSora = Sora({ subsets: ['latin'], weight: '500', variable: '--font-inter', })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Start Learning: 
// https://nextjs.org/docs/pages/api-reference/components/font

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fontSora.className}>
        {children}
      </body>
    </html>
  )
}
